/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/bigSizeRound.glb -o src/components/Castle/Object/BigSizeRound.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BigSizeRound(props) {
  const { nodes, materials } = useGLTF('/assets/models/bigSizeRound.glb')
  return (
    <group {...props} dispose={null}>
        <group  position={[-1.774, -0.959, 2.014]} rotation={[Math.PI / 2, 0, 0]} scale={[0.014, 0.015, 0.025]}>
            <mesh geometry={nodes.Dungeon_Big_to_Custom.geometry} material={materials['Stone_Wall.001']} />
        </group>
    </group>
  )
}

export function BigSizeRound1(props) {
    const { nodes, materials } = useGLTF('/assets/models/bigSizeRound.glb')
    return (
      <group {...props} dispose={null}>
          <group rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
              <mesh geometry={nodes.Dungeon_Big_to_Custom.geometry} material={materials['Stone_Wall.001']} />
          </group>
      </group>
    )
  }

useGLTF.preload('/assets/models/bigSizeRound.glb')
