/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/greek columns.glb -o src/Castle/Object/Columns.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Columns(props) {
  const { nodes, materials } = useGLTF('/assets/models/greek columns.glb')
  return (
    <group {...props} dispose={null}>
        <group rotation={[0, 0, 0]} scale={5}>
            <mesh geometry={nodes.group2092667859.geometry} material={materials.mat21} />
        </group>
    </group>
  )
}

useGLTF.preload('/assets/models/greek columns.glb')