/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/firePlace.glb -o src/components/Castle/Object/FirePlace.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FirePlace(props) {
  const { nodes, materials } = useGLTF('/assets/models/firePlace.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI]} scale={0.012}>
        <mesh geometry={nodes.Scene046.geometry} material={materials['Metal_Rusty.004']} />
        <mesh geometry={nodes.Scene046_1.geometry} material={materials['Stone_Wall.008']} />
        <mesh geometry={nodes.Scene046_2.geometry} material={materials['Wood_Basic.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/firePlace.glb')
