/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Pedestal.glb -o src/components/Castle/Object/Pedestal.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pedestal(props) {
  const { nodes, materials } = useGLTF('/assets/models/Pedestal.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pedestal2.geometry} material={materials.Marble} rotation={[-Math.PI / 2, 0, 0]} scale={[250, 250, 520]} />
    </group>
  )
}

useGLTF.preload('/assets/models/Pedestal.glb')
