/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/signRedWhite.glb -o src/components/Castle/Object/SignRed.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SignRed(props) {
  const { nodes, materials } = useGLTF('/assets/models/signRedWhite.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sign_free.geometry} material={materials.Environment_Free_Material} rotation={[Math.PI / 2, 0, -Math.PI/2]} scale={0.03} />
    </group>
  )
}

useGLTF.preload('/assets/models/signRedWhite.glb')
