/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/signWhiteArrow.glb -o src/components/Object/Sign.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sign(props) { // 오른쪽 화살표 ( 가로 )
  const { nodes, materials } = useGLTF('/assets/models/signWhiteArrow.glb')
  return (
    <group {...props} dispose={null}>
        <group rotation={[-Math.PI/2, Math.PI/2, 0]} scale={0.005}>
            <mesh geometry={nodes.Arrow_02_free.geometry} material={materials['Environment_Free_Material.001']} />
        </group>
    </group>
  )
}

export function Sign2(props) { // 왼쪽 화살표 ( 가로 )
  const { nodes, materials } = useGLTF('/assets/models/signWhiteArrow.glb')
  return (
    <group {...props} dispose={null}>
        <group rotation={[Math.PI/2, Math.PI/2, 0]} scale={0.005}>
            <mesh geometry={nodes.Arrow_02_free.geometry} material={materials['Environment_Free_Material.001']} />
        </group>
    </group>
  )
}

export function Sign3(props) { // 왼쪽 화살표 ( 세로 )
  const { nodes, materials } = useGLTF('/assets/models/signWhiteArrow.glb')
  return (
    <group {...props} dispose={null}>
        <group rotation={[0, 0, Math.PI/2]} scale={0.005}>
            <mesh geometry={nodes.Arrow_02_free.geometry} material={materials['Environment_Free_Material.001']} />
        </group>
    </group>
  )
}

export function Sign4(props) { // 오른쪽 화살표 ( 세로 )
  const { nodes, materials } = useGLTF('/assets/models/signWhiteArrow.glb')
  return (
    <group {...props} dispose={null}>
        <group rotation={[0, 0 , -Math.PI/2]} scale={0.005}>
            <mesh geometry={nodes.Arrow_02_free.geometry} material={materials['Environment_Free_Material.001']} />
        </group>
    </group>
  )
}

useGLTF.preload('/assets/models/signWhiteArrow.glb')
