/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Statue.glb -o src/Castle/Object/Statue.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Statue(props) {
    const { nodes, materials } = useGLTF('/assets/models/Statue.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[0, 0, 0]} scale={5}>
                <mesh geometry={nodes.Statue2.geometry} material={materials.Statue2} />
            </group>
        </group>
    )
}

export function Statue1(props) {
    const { nodes, materials } = useGLTF('/assets/models/Statue1.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[0, 0, 0]} scale={5}>
                <mesh geometry={nodes.Statue4.geometry} material={materials.Statue4} />
            </group>
        </group>
    )
}

export function Statue2(props) {
    const { nodes, materials } = useGLTF('/assets/models/Statue2.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[0, Math.PI, 0]} scale={5}>
                <mesh geometry={nodes.Statue6.geometry} material={materials.Statue6} />
            </group>
        </group>
    )
}

export function Statue3(props) {
    const { nodes, materials } = useGLTF('/assets/models/Statue3.glb')
    return (
        <group {...props} dispose={null}>
            <group group rotation={[0, Math.PI, 0]} scale={3}>
                <mesh geometry={nodes.Statue1.geometry} material={materials.Statue1} />
            </group>
        </group>
    )
}

export function Statue4(props) {
    const { nodes, materials } = useGLTF('/assets/models/Statue3.glb')
    return (
        <group {...props} dispose={null}>
            <group group rotation={[0, 0, 0]} scale={3}>
                <mesh geometry={nodes.Statue1.geometry} material={materials.Statue1} />
            </group>
        </group>
    )
}
  
useGLTF.preload('/assets/models/Statue.glb')
useGLTF.preload('/assets/models/Statue1.glb')
useGLTF.preload('/assets/models/Statue2.glb')
useGLTF.preload('/assets/models/Statue3.glb')