/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/graybasketballcourt3.glb -o src/components/resort/Basketball.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BasketballCourt(props) {
  const { nodes, materials } = useGLTF('/assets/models/graybasketballcourt3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BasketBallCourt_Mesh.geometry} material={materials.BasketBallCourt_mat} />
    </group>
  )
}

useGLTF.preload('/assets/models/graybasketballcourt3.glb')
