/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Bridge.glb -o src/components/resort/Bridge.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bridge(props) {
  const { nodes, materials } = useGLTF('/assets/models/Bridge.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Bridge.geometry} material={materials.Diffuse_color} scale={700} />
    </group>
  )
}

useGLTF.preload('/assets/models/Bridge.glb')
