/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Buildings.glb -o src/components/resort/Buildings.jsx -r public -s 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Building_1_Red(props) {
  const { nodes, materials } = useGLTF('/assets/models/Building_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
      <mesh castShadow receiveShadow geometry={nodes.Scene407.geometry} material={materials['Brick_walls_2_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_1.geometry} material={materials['Walls_1.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_2.geometry} material={materials['Doors.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_3.geometry} material={materials['Parts.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_4.geometry} material={materials['Tile_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_5.geometry} material={materials['Plinth_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_6.geometry} material={materials['Roof.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_7.geometry} material={materials['Stairs.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_8.geometry} material={materials['Walls_2_3.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_9.geometry} material={materials['Windows.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_10.geometry} material={materials['Airing.005']} />
      </group>
    </group>
  )
}

export function Building_5_Red(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
          <mesh castShadow receiveShadow geometry={nodes.Scene411.geometry} material={materials['Roof.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_1.geometry} material={materials['Parts.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_2.geometry} material={materials['Walls_4.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_3.geometry} material={materials['Doors.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_4.geometry} material={materials['Plinth_3.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_5.geometry} material={materials['Stairs.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_6.geometry} material={materials['Brick_walls_2_1.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_7.geometry} material={materials['Brick_walls_1.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_8.geometry} material={materials['Walls_1_3.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_9.geometry} material={materials['Windows.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_10.geometry} material={materials['Airing.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_11.geometry} material={materials['Solar_panel.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene411_12.geometry} material={materials['Wall_clumb.004']} />
      </group>
    </group>
  )
}

export function Building_9_Red(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
        <group position={[0, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Scene416.geometry} material={materials['Roof.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene416_1.geometry} material={materials['Walls_1.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene416_2.geometry} material={materials['Doors.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene416_3.geometry} material={materials['Plinth_3.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene416_4.geometry} material={materials['Stairs.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene416_5.geometry} material={materials['Brick_walls_2_1.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene416_6.geometry} material={materials['Brick_walls_2.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene416_7.geometry} material={materials['Windows.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene416_8.geometry} material={materials['Airing.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene416_9.geometry} material={materials['Awnings_2.005']} />
        </group>
      </group>
    </group>
  )
}

export function Building_8_Red(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
        <mesh castShadow receiveShadow geometry={nodes.Scene419.geometry} material={materials['Roof.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_1.geometry} material={materials['Shutters.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_2.geometry} material={materials['Windows.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_3.geometry} material={materials['Walls_4_2.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_4.geometry} material={materials['Brick_walls_1.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_5.geometry} material={materials['Walls_2.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_6.geometry} material={materials['Stairs.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_7.geometry} material={materials['Plinth_1.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_8.geometry} material={materials['Doors.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_9.geometry} material={materials['Walls_3.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_10.geometry} material={materials['Parts.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_11.geometry} material={materials['Awnings_2.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene419_12.geometry} material={materials['Airing.006']} />
      </group>
    </group>
  )
}

export function Building_10_Red(props) {
  const { nodes, materials } = useGLTF('/assets/models/Building_10-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene010.geometry} material={materials['Roof.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_1.geometry} material={materials['Walls_4.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_2.geometry} material={materials['Walls_1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_3.geometry} material={materials['Doors.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_4.geometry} material={materials['Plinth_3.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_5.geometry} material={materials['Stairs.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_6.geometry} material={materials['Walls_6.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_7.geometry} material={materials['Walls_1_3.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_8.geometry} material={materials['Windows.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_9.geometry} material={materials['Airing.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_10.geometry} material={materials['Awnings.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene010_11.geometry} material={materials['Shutters.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_10-transformed.glb')


export function Building_2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/models/Building_2-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Building_2" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="Building_2_Roof">
            <mesh name="Scene003" castShadow receiveShadow geometry={nodes.Scene003.geometry} material={materials['Roof.002']} />
            <mesh name="Scene003_1" castShadow receiveShadow geometry={nodes.Scene003_1.geometry} material={materials['Walls_3.001']} />
            <mesh name="Scene003_2" castShadow receiveShadow geometry={nodes.Scene003_2.geometry} material={materials['Walls_1.002']} />
            <mesh name="Scene003_3" castShadow receiveShadow geometry={nodes.Scene003_3.geometry} material={materials['Doors.002']} />
            <mesh name="Scene003_4" castShadow receiveShadow geometry={nodes.Scene003_4.geometry} material={materials['Wood.001']} />
            <mesh name="Scene003_5" castShadow receiveShadow geometry={nodes.Scene003_5.geometry} material={materials['Plinth_2.001']} />
            <mesh name="Scene003_6" castShadow receiveShadow geometry={nodes.Scene003_6.geometry} material={materials['Stairs.002']} />
            <mesh name="Scene003_7" castShadow receiveShadow geometry={nodes.Scene003_7.geometry} material={materials['Brick_walls_1_1.001']} />
            <mesh name="Scene003_8" castShadow receiveShadow geometry={nodes.Scene003_8.geometry} material={materials['Walls_2_3.002']} />
            <mesh name="Scene003_9" castShadow receiveShadow geometry={nodes.Scene003_9.geometry} material={materials['Windows.002']} />
            <mesh name="Scene003_10" castShadow receiveShadow geometry={nodes.Scene003_10.geometry} material={materials['Airing.002']} />
            <mesh name="Scene003_11" castShadow receiveShadow geometry={nodes.Scene003_11.geometry} material={materials['Parts.002']} />
            <mesh name="Scene003_12" castShadow receiveShadow geometry={nodes.Scene003_12.geometry} material={materials['Awnings_2.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_2-transformed.glb')

export function Building_3_Red(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
        <mesh castShadow receiveShadow geometry={nodes.Scene409.geometry} material={materials['Parts.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_1.geometry} material={materials['Walls_3.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_2.geometry} material={materials['Walls_4.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_3.geometry} material={materials['Doors.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_4.geometry} material={materials['Tile_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_5.geometry} material={materials['Plinth_3.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_6.geometry} material={materials['Roof.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_7.geometry} material={materials['Stairs.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_8.geometry} material={materials['Brick_walls_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_9.geometry} material={materials['Walls_1.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_10.geometry} material={materials['Walls_2_3.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_11.geometry} material={materials['Windows.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_12.geometry} material={materials['Airing.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_13.geometry} material={materials['Shutters.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene409_14.geometry} material={materials['Wall_clumb.004']} />
      </group>
    </group>
  )
}

export function Building_4_Red(props) {
  const { nodes, materials } = useGLTF('/assets/models/Building_4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene005.geometry} material={materials['Walls_2_3.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_1.geometry} material={materials['Walls_3.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_2.geometry} material={materials['Walls_4.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_3.geometry} material={materials['Doors.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_4.geometry} material={materials['Parts.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_5.geometry} material={materials['Wood.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_6.geometry} material={materials['Plinth_3.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_7.geometry} material={materials['Roof.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_8.geometry} material={materials['Stairs.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_9.geometry} material={materials['Brick_walls_2_1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_10.geometry} material={materials['Windows.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_11.geometry} material={materials['Airing.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_12.geometry} material={materials['Wall_clumb.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene005_13.geometry} material={materials['Walls_3_2.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_4-transformed.glb')

export function Building_6_Green(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Scene418.geometry} material={materials['Roof.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_1.geometry} material={materials['Walls_6.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_2.geometry} material={materials['Walls_1.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_3.geometry} material={materials['Walls_4.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_4.geometry} material={materials['Doors.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_5.geometry} material={materials['Plinth_1.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_6.geometry} material={materials['Stairs.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_7.geometry} material={materials['Walls_5_2.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_8.geometry} material={materials['Walls_1_2.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_9.geometry} material={materials['Walls_5.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_10.geometry} material={materials['Walls_2_2.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_11.geometry} material={materials['Windows.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_12.geometry} material={materials['Airing.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_13.geometry} material={materials['Wall_clumb.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene418_14.geometry} material={materials['Shutters.005']} />
        </group>
      </group>
    </group>
  )
}

export function Building_5_Green(props) {
  const { nodes, materials } = useGLTF('/assets/models/Building_5-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene018.geometry} material={materials['Walls_1.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_1.geometry} material={materials['Walls_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_2.geometry} material={materials['Wall_clumb.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_3.geometry} material={materials['Solar_panel.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_4.geometry} material={materials['Windows.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_5.geometry} material={materials['Walls_2_3.008']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_6.geometry} material={materials['Walls_1_3.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_7.geometry} material={materials['Brick_walls_1_1.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_8.geometry} material={materials['Stairs.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_9.geometry} material={materials['Roof.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_10.geometry} material={materials['Plinth_2.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_11.geometry} material={materials['Doors.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_12.geometry} material={materials['Walls_5.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_13.geometry} material={materials['Parts.010']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_14.geometry} material={materials['Airing.014']} />
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_5-transformed.glb')

export function Building_8_Green(props) {
  const { nodes, materials } = useGLTF('/assets/models/Building_8-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene015.geometry} material={materials['Walls_4.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_1.geometry} material={materials['Parts.009']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_2.geometry} material={materials['Doors.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_3.geometry} material={materials['Plinth_3.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_4.geometry} material={materials['Roof.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_5.geometry} material={materials['Stairs.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_6.geometry} material={materials['Walls_2_3.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_7.geometry} material={materials['Walls_5.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_8.geometry} material={materials['Walls_5_2.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_9.geometry} material={materials['Windows.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_10.geometry} material={materials['Airing.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_11.geometry} material={materials['Awnings_2.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene015_12.geometry} material={materials['Shutters.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_8-transformed.glb')

export function Building_10_1_Blue(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
        <group position={[0, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Scene413.geometry} material={materials['Roof.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_1.geometry} material={materials['Walls_4.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_2.geometry} material={materials['Walls_1.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_3.geometry} material={materials['Doors.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_4.geometry} material={materials['Plinth_2.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_5.geometry} material={materials['Stairs.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_6.geometry} material={materials['Walls_2_2.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_7.geometry} material={materials['Walls_6.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_8.geometry} material={materials['Windows.005']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_9.geometry} material={materials['Awnings.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Scene413_10.geometry} material={materials['Airing.005']} />
        </group>
      </group>
    </group>
  )
}

export function Building_10_Blue(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
        <mesh castShadow receiveShadow geometry={nodes.Airing_4__1__3.geometry} material={materials['Airing.005']} rotation={[0, 0, 1.571]} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415.geometry} material={materials['Roof.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_1.geometry} material={materials['Walls_4.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_2.geometry} material={materials['Walls_1.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_3.geometry} material={materials['Doors.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_4.geometry} material={materials['Plinth_3.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_5.geometry} material={materials['Stairs.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_6.geometry} material={materials['Walls_6.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_7.geometry} material={materials['Walls_1_3.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_8.geometry} material={materials['Windows.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_9.geometry} material={materials['Airing.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_10.geometry} material={materials['Awnings.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene415_11.geometry} material={materials['Shutters.005']} />
      </group>
    </group>
  )
}

export function Building_9_Blue(props) {
  const { nodes, materials } = useGLTF('/assets/models/Building_9-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene011.geometry} material={materials['Roof.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_1.geometry} material={materials['Walls_1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_2.geometry} material={materials['Doors.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_3.geometry} material={materials['Plinth_3.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_4.geometry} material={materials['Stairs.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_5.geometry} material={materials['Brick_walls_2_1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_6.geometry} material={materials['Brick_walls_2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_7.geometry} material={materials['Windows.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_8.geometry} material={materials['Airing.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_9.geometry} material={materials['Awnings_2.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_9-transformed.glb')

export function Building_7_Blue(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
        <mesh castShadow receiveShadow geometry={nodes.Scene417.geometry} material={materials['Roof.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_1.geometry} material={materials['Walls_6.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_2.geometry} material={materials['Doors.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_3.geometry} material={materials['Parts.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_4.geometry} material={materials['Tile_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_5.geometry} material={materials['Plinth_3.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_6.geometry} material={materials['Stairs.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_7.geometry} material={materials['Brick_walls_1_1.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_8.geometry} material={materials['Walls_6_2.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_9.geometry} material={materials['Walls_2_3.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_10.geometry} material={materials['Windows.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_11.geometry} material={materials['Airing.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_12.geometry} material={materials['Awnings.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene417_13.geometry} material={materials['Wall_clumb.004']} />
      </group>
    </group>
  )
}


useGLTF.preload('/assets/models/Buildings.glb')