/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Metalfence.glb -o src/components/resort/Metalfence.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Metalfence(props) {
  const { nodes, materials } = useGLTF('/assets/models/Metalfence.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Fence_Cylinder.geometry} material={materials.Silver} />
    </group>
  )
}

useGLTF.preload('/assets/models/Metalfence.glb')
