/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\assets\models\resort-buildings.glb -o src/components/resort-buildings.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CurbStraightHalf(props) {
  
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Border_half.geometry} material={materials.Border_road_props} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
      
  )
}

export function CurbStraight(props) {
  
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Border_1.geometry} material={materials.Border_road_props} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
      
  )
}

export function CurbLeftBottomCurve(props) {
  
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Border_3.geometry} material={materials.Border_road_props} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
      
  )
}

export function CurbRightTopLongCurve(props) {
  
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Border_4.geometry} material={materials.Border_road_props} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
      
  )
}

export function CurbRightBottomCurve(props) {
  
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Border_4_1.geometry} material={materials.Border_road_props} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
      
  )
}

export function CurbRightTopCurve1(props) {
  
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Border_5.geometry} material={materials.Border_road_props} position={[-21.417, -0.075, -5.86]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
      
  )
}
export function CurbRightTopCurve2(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Border_2.geometry} material={materials.Border_road_props} position={[-29.133, -0.075, -4.625]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function GrassPlain(props) {
  
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass.geometry} material={materials.Grass} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
      
  )
}
export function RoadLanes (props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Road_1.geometry} material={materials.Asphalt} position={[0, 0, 0]} rotation={[Math.PI/2, 0, 0]} scale={0.01} />
    </group>
  )
}
export function CrossWalkTop(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Road_2.geometry} material={materials.Asphalt_2} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />

    </group>
  )
}
export function RoadPlain(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Road_3.geometry} material={materials.Asphalt_3} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function RoadLeftBottomCurve(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Road_4.geometry} material={materials.Asphalt_4} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function CrossWalkHalf(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Road_half.geometry} material={materials.Asphalt_2} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function PlainRoadHalf(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Road_half_2.geometry} material={materials.Asphalt_2} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}
export function RoadLanesHalf(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Road_half_4.geometry} material={materials.Asphalt} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />

    </group>
  )
}
export function SideLeftBottom(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Road_half_3.geometry} material={materials.Asphalt_3} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}
export function Side2(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />

    </group>
  )
}
export function Side(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_2.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}
export function SideRightTopCurveLong(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_corner.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}
export function SideRightTopCurve(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_corner_1.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}
export function SideRightTopInnerCurve(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_corner_3.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />

    </group>
  )
}
export function SideRightTopInnerCurve2(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_corner_4.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}
export function SideRightTopOutterCurve1(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_corner_5.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />

    </group>
  )
}
export function SideRightTopOutterCurve2(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_corner_6.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function SideRightTopInnerCurve3(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_corner_7.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />

    </group>
  )
}
export function Side3(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-roads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_half.geometry} material={materials.Sidewalk} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}


useGLTF.preload('/assets/models/resort-buildings.glb')
useGLTF.preload('/assets/models/resort-road.glb')


