/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\assets\models\Rover.glb -o src/components/resort/Rover.jsx -r public -s 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Rover(props) {
  const { nodes, materials } = useGLTF('/assets/models/Rover.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Wheel_4001.geometry} material={materials.Atlas} position={[-1.796, 0.526, 1.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Wheel_5.geometry} material={materials.Atlas} position={[1.796, 0.526, 1.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Wheel_1002.geometry} material={materials.Atlas} position={[1.796, 0.526, -1.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Wheel_4002.geometry} material={materials.Atlas} position={[-1.796, 0.526, -1.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Rover_1.geometry} material={materials.Atlas} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/assets/models/Rover.glb')
