/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/signs.glb -o src/components/resort/Signs.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Corner_Sign_Left(props) {
  const { nodes, materials } = useGLTF('/assets/models/signs.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[-0.13, -0.13, -1]}>
            <mesh geometry={nodes.Scene004.geometry} material={materials.Sign_Sharp_Right} />
            <mesh geometry={nodes.Scene004_1.geometry} material={materials.Sign_Post_1} />
          </group>
      </group>
    </group>
  )
}

export function Corner_Sign_Right(props) {
  const { nodes, materials } = useGLTF('/assets/models/signs.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.25, 1]}>
          <mesh geometry={nodes.Scene006.geometry} material={materials.Sign_Post_2} />
          <mesh geometry={nodes.Scene006_1.geometry} material={materials.Sign_Sharp_Right} />
        </group>
      </group>
    </group>
  )
}

export function Corner_Sign_Speedlimit(props) {
  const { nodes, materials } = useGLTF('/assets/models/signs.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={[0.081, 0.1, 1]}>
            <mesh geometry={nodes.Scene004_2.geometry} material={materials.Sign_Speed_55} />
            <mesh geometry={nodes.Scene004_3.geometry} material={materials.Sign_Post_1} />
          </group>
      </group>
    </group>
  )
}


useGLTF.preload('/assets/models/signs.glb')
