/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/BananaCar.glb -o src/components/BananaCar.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BananaCar(props) {
  const { nodes, materials } = useGLTF('/assets/models/BananaCar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.chair.geometry} material={materials.leather_black} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.DefaultMaterial} />
      <mesh geometry={nodes.arm_1.geometry} material={materials.black_arm} />
      <mesh geometry={nodes.arm_1_1.geometry} material={materials.chrome} />
      <mesh geometry={nodes.arm_1_2.geometry} material={materials.black_arm} />
      <mesh geometry={nodes.arm_1_2_1.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.black_arm} />
      <mesh geometry={nodes.arm_1_3.geometry} material={materials.black_arm} />
      <mesh geometry={nodes.arm_1_3_1.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Torus.geometry} material={materials.leather_black} />
      <mesh geometry={nodes.windshield.geometry} material={materials.banana_glass} />
      <mesh geometry={nodes.windshield_1.geometry} material={materials.windshiledrinm} />
      <mesh geometry={nodes.tire.geometry} material={materials.tire_mat} />
      <mesh geometry={nodes.axel.geometry} material={materials.DefaultMaterial} />
      <mesh geometry={nodes.wheel_support.geometry} material={materials.DefaultMaterial} />
      <mesh geometry={nodes.axel_2.geometry} material={materials.DefaultMaterial} />
      <mesh geometry={nodes.tire_2.geometry} material={materials.tire_mat} />
      <mesh geometry={nodes.tire_3.geometry} material={materials.tire_mat} />
      <mesh geometry={nodes.body.geometry} material={materials.banana_yellow} />
    </group>
  )
}

useGLTF.preload('/assets/models/BananaCar.glb')
