/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Bookshelf.glb -o src/components/BookShelf.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three'
import {useBox} from '@react-three/cannon'




export function BookShelf(props) {
  const { nodes, materials } = useGLTF('/assets/models/Bookshelf.glb')

  return (

    
      <group {...props} dispose={null}>
      
      <mesh geometry={nodes.group966664866.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1048815158.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1702132102.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group633938376.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1793352265.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group2040108076.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group634255084.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1359852237.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1987144854.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group751481862.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group227914780.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1052635492.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group864707251.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group687955143.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1751088038.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group505671632.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group283918997.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group165613401.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group14247407.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1938683590.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group423249565.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group802050906.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1003306018.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group875940139.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group552841683.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1357238172.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1138996592.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1331048207.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group752636525.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1447785718.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1387497183.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group156460083.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group438200932.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group257976566.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group2006398532.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1479453844.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1662040012.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1484951833.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group752053113.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group937831915.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group225002350.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group905252152.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group59390808.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1692817625.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group256395068.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group611048843.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1034316329.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1994798792.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group250223753.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group286116515.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group13306777.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group2015271255.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1782243135.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group962457873.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1019897031.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group2095556955.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1011911227.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group15835575.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1017517075.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1721710528.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group380733211.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group548630757.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group728145106.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1812224903.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1366047388.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1838312899.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1972613599.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group213039448.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1839125294.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1967720642.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1884002018.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group842451926.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1011320071.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group935609718.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1699351704.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group370983626.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group192929773.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1220427099.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1370981756.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1497847545.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group238343898.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1849838348.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1798431221.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1277222791.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1146959302.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1632347617.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group633143504.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1269888978.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1573889920.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group93335299.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1140854425.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1140854425_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1140854425_2.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1140854425_3.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1140854425_4.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1140854425_5.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1140854425_6.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh742438179.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh742438179_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh742438179_2.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh742438179_3.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh742438179_4.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh742438179_5.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh742438179_6.geometry} material={materials.mat20} />
    </group>
  )
}

useGLTF.preload('/assets/models/Bookshelf.glb')
