/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Building_1.glb -o src/components/Buildings_1.jsx -r public/ -T -s 
Files: public/assets/models/Building_1.glb [1.14MB] > C:\Users\푸린\Desktop\activity\jungle\project0100\front\src\components\Building_1-transformed.glb [236.59KB] (79%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/../src/components/Building_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene407.geometry} material={materials['Brick_walls_2_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_1.geometry} material={materials['Walls_1.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_2.geometry} material={materials['Doors.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_3.geometry} material={materials['Parts.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_4.geometry} material={materials['Tile_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_5.geometry} material={materials['Plinth_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_6.geometry} material={materials['Roof.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_7.geometry} material={materials['Stairs.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_8.geometry} material={materials['Walls_2_3.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_9.geometry} material={materials['Windows.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene407_10.geometry} material={materials['Airing.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_1-transformed.glb')
