/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Building_9.glb -o src/components/Building_9.jsx -r public/ -s -S -T 
Files: public/assets/models/Building_9.glb [1.55MB] > C:\Users\푸린\Desktop\activity\jungle\project0100\front\src\components\Building_9-transformed.glb [239.76KB] (85%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/../src/components/Building_9-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene011.geometry} material={materials['Roof.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_1.geometry} material={materials['Walls_1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_2.geometry} material={materials['Doors.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_3.geometry} material={materials['Plinth_3.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_4.geometry} material={materials['Stairs.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_5.geometry} material={materials['Brick_walls_2_1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_6.geometry} material={materials['Brick_walls_2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_7.geometry} material={materials['Windows.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_8.geometry} material={materials['Airing.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene011_9.geometry} material={materials['Awnings_2.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_9-transformed.glb')
