/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Buildings.glb -o src/components/Buildings_trans.jsx -r --transform public/ 
Files: public/assets/models/Buildings.glb [4MB] > C:\Users\푸린\Desktop\activity\jungle\project0100\front\src\components\Buildings-transformed.glb [1.11MB] (72%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Buildings_trans(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings_transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-9.957, -6.147, -12.326]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene407.geometry} material={materials['Brick_walls_2_1.004']} />
        <mesh geometry={nodes.Scene407_1.geometry} material={materials['Walls_1.005']} />
        <mesh geometry={nodes.Scene407_2.geometry} material={materials['Doors.005']} />
        <mesh geometry={nodes.Scene407_3.geometry} material={materials['Parts.004']} />
        <mesh geometry={nodes.Scene407_4.geometry} material={materials['Tile_1.004']} />
        <mesh geometry={nodes.Scene407_5.geometry} material={materials['Plinth_1.004']} />
        <mesh geometry={nodes.Scene407_6.geometry} material={materials['Roof.005']} />
        <mesh geometry={nodes.Scene407_7.geometry} material={materials['Stairs.005']} />
        <mesh geometry={nodes.Scene407_8.geometry} material={materials['Walls_2_3.004']} />
        <mesh geometry={nodes.Scene407_9.geometry} material={materials['Windows.005']} />
        <mesh geometry={nodes.Scene407_10.geometry} material={materials['Airing.005']} />
      </group>
      <group position={[-4.064, -3.848, -19.335]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene408.geometry} material={materials['Walls_3.005']} />
        <mesh geometry={nodes.Scene408_1.geometry} material={materials['Wood.004']} />
        <mesh geometry={nodes.Scene408_2.geometry} material={materials['Plinth_2.004']} />
        <mesh geometry={nodes.Scene408_3.geometry} material={materials['Brick_walls_1_1.005']} />
        <mesh geometry={nodes.Scene408_4.geometry} material={materials['Awnings_2.005']} />
      </group>
      <group position={[4.122, -8.705, -9.058]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene409.geometry} material={materials['Walls_4.005']} />
        <mesh geometry={nodes.Scene409_1.geometry} material={materials['Plinth_3.005']} />
        <mesh geometry={nodes.Scene409_2.geometry} material={materials['Brick_walls_1.004']} />
        <mesh geometry={nodes.Scene409_3.geometry} material={materials['Shutters.005']} />
        <mesh geometry={nodes.Scene409_4.geometry} material={materials['Wall_clumb.004']} />
      </group>
      <mesh geometry={nodes.Building_4_Walls_2.geometry} material={materials['Walls_3_2.004']} position={[6.242, 0.75, -22.526]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[16.3, 7.611, -13.882]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene411.geometry} material={materials['Walls_1_3.004']} />
        <mesh geometry={nodes.Scene411_1.geometry} material={materials['Solar_panel.004']} />
      </group>
      <group position={[19.022, 0.341, -5.772]} scale={0.01}>
        <mesh geometry={nodes.Scene412.geometry} material={materials['Walls_2.005']} />
        <mesh geometry={nodes.Scene412_1.geometry} material={materials['Walls_6.004']} />
        <mesh geometry={nodes.Scene412_2.geometry} material={materials['Walls_5_2.004']} />
        <mesh geometry={nodes.Scene412_3.geometry} material={materials['Walls_1_2.004']} />
        <mesh geometry={nodes.Scene412_4.geometry} material={materials['Walls_5.004']} />
        <mesh geometry={nodes.Scene412_5.geometry} material={materials['Walls_2_2.005']} />
        <mesh geometry={nodes.Scene412_6.geometry} material={materials['Brick_walls_2.004']} />
      </group>
      <mesh geometry={nodes.Building_10_1_Roof_1.geometry} material={materials['Awnings.004']} position={[49.354, -7.177, -18.71]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Building_7_Roof.geometry} material={materials['Walls_6_2.004']} position={[12.471, -10.928, 27.289]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[-31.029, -10.928, 23.089]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene419.geometry} material={materials['Walls_4_2.004']} />
        <mesh geometry={nodes.Scene419_1.geometry} material={materials['Parts.005']} />
      </group>
      <mesh geometry={nodes.Building_8_Decor_1_1.geometry} material={materials['Walls_2_3.005']} position={[-11.409, -10.928, 23.439]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Building_10_Walls_1.geometry} material={materials['Brick_walls_1_1.006']} position={[-22.052, -8.291, -36.367]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Airing_2__6_.geometry} material={materials['Airing.009']} position={[51.749, -14.996, -14.848]} rotation={[Math.PI / 2, 0, 1.571]} scale={0.01} />
      <mesh geometry={nodes.Building_5_Decor_2.geometry} material={materials['Walls_1.006']} position={[21.407, -19.467, 0.024]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Buildings-transformed.glb')
