/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Building_2.glb -o src/components/Building_2.jsx -r public/ -s -S -T 
Files: public/assets/models/Building_2.glb [1.33MB] > C:\Users\푸린\Desktop\activity\jungle\project0100\front\src\components\Building_2-transformed.glb [273.08KB] (79%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/../src/components/Building_2-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Building_2" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="Building_2_Roof">
            <mesh name="Scene003" castShadow receiveShadow geometry={nodes.Scene003.geometry} material={materials['Roof.002']} />
            <mesh name="Scene003_1" castShadow receiveShadow geometry={nodes.Scene003_1.geometry} material={materials['Walls_3.001']} />
            <mesh name="Scene003_2" castShadow receiveShadow geometry={nodes.Scene003_2.geometry} material={materials['Walls_1.002']} />
            <mesh name="Scene003_3" castShadow receiveShadow geometry={nodes.Scene003_3.geometry} material={materials['Doors.002']} />
            <mesh name="Scene003_4" castShadow receiveShadow geometry={nodes.Scene003_4.geometry} material={materials['Wood.001']} />
            <mesh name="Scene003_5" castShadow receiveShadow geometry={nodes.Scene003_5.geometry} material={materials['Plinth_2.001']} />
            <mesh name="Scene003_6" castShadow receiveShadow geometry={nodes.Scene003_6.geometry} material={materials['Stairs.002']} />
            <mesh name="Scene003_7" castShadow receiveShadow geometry={nodes.Scene003_7.geometry} material={materials['Brick_walls_1_1.001']} />
            <mesh name="Scene003_8" castShadow receiveShadow geometry={nodes.Scene003_8.geometry} material={materials['Walls_2_3.002']} />
            <mesh name="Scene003_9" castShadow receiveShadow geometry={nodes.Scene003_9.geometry} material={materials['Windows.002']} />
            <mesh name="Scene003_10" castShadow receiveShadow geometry={nodes.Scene003_10.geometry} material={materials['Airing.002']} />
            <mesh name="Scene003_11" castShadow receiveShadow geometry={nodes.Scene003_11.geometry} material={materials['Parts.002']} />
            <mesh name="Scene003_12" castShadow receiveShadow geometry={nodes.Scene003_12.geometry} material={materials['Awnings_2.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_2-transformed.glb')
