/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\assets\models\Buildings_mod.glb -o src/components/Buildings_mod.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/Buildings_mod.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-31.766, -10.928, -8.053]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene001.geometry} material={materials.Walls_1} />
        <mesh geometry={nodes.Scene001_1.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene001_2.geometry} material={materials.Parts} />
        <mesh geometry={nodes.Scene001_3.geometry} material={materials.Tile_1} />
        <mesh geometry={nodes.Scene001_4.geometry} material={materials.Plinth_1} />
        <mesh geometry={nodes.Scene001_5.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene001_6.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene001_7.geometry} material={materials.Brick_walls_2_1} />
        <mesh geometry={nodes.Scene001_8.geometry} material={materials.Walls_2_3} />
        <mesh geometry={nodes.Scene001_9.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene001_10.geometry} material={materials.Airing} />
      </group>
      <group position={[-20.535, -10.928, -8.554]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[725.584, 264.925, -145.598]}>
          <mesh geometry={nodes.Scene017.geometry} material={materials.Roof} />
          <mesh geometry={nodes.Scene017_1.geometry} material={materials.Walls_3} />
          <mesh geometry={nodes.Scene017_2.geometry} material={materials.Walls_1} />
          <mesh geometry={nodes.Scene017_3.geometry} material={materials.Doors} />
          <mesh geometry={nodes.Scene017_4.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Scene017_5.geometry} material={materials.Plinth_2} />
          <mesh geometry={nodes.Scene017_6.geometry} material={materials.Stairs} />
          <mesh geometry={nodes.Scene017_7.geometry} material={materials.Brick_walls_1_1} />
          <mesh geometry={nodes.Scene017_8.geometry} material={materials.Walls_2_3} />
          <mesh geometry={nodes.Scene017_9.geometry} material={materials.Windows} />
          <mesh geometry={nodes.Scene017_10.geometry} material={materials.Airing} />
          <mesh geometry={nodes.Scene017_11.geometry} material={materials.Parts} />
          <mesh geometry={nodes.Scene017_12.geometry} material={materials.Awnings_2} />
        </group>
      </group>
      <group position={[-9.221, -10.928, -8.834]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-2166.257, -2999.166, -306.709]}>
          <mesh geometry={nodes.Scene033.geometry} material={materials.Tile_1} />
          <mesh geometry={nodes.Scene033_1.geometry} material={materials.Parts} />
          <mesh geometry={nodes.Scene033_2.geometry} material={materials.Walls_3} />
          <mesh geometry={nodes.Scene033_3.geometry} material={materials.Walls_4} />
          <mesh geometry={nodes.Scene033_4.geometry} material={materials.Doors} />
          <mesh geometry={nodes.Scene033_5.geometry} material={materials.Plinth_3} />
          <mesh geometry={nodes.Scene033_6.geometry} material={materials.Roof} />
          <mesh geometry={nodes.Scene033_7.geometry} material={materials.Stairs} />
          <mesh geometry={nodes.Scene033_8.geometry} material={materials.Brick_walls_1} />
          <mesh geometry={nodes.Scene033_9.geometry} material={materials.Walls_1} />
          <mesh geometry={nodes.Scene033_10.geometry} material={materials.Walls_2_3} />
          <mesh geometry={nodes.Scene033_11.geometry} material={materials.Windows} />
          <mesh geometry={nodes.Scene033_12.geometry} material={materials.Airing} />
          <mesh geometry={nodes.Scene033_13.geometry} material={materials.Shutters} />
          <mesh geometry={nodes.Scene033_14.geometry} material={materials.Wall_clumb} />
        </group>
      </group>
      <group position={[12.127, -10.928, -9.119]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[250, 136, -1049]}>
          <mesh geometry={nodes.Scene068.geometry} material={materials.Solar_panel} />
          <mesh geometry={nodes.Scene068_1.geometry} material={materials.Parts} />
          <mesh geometry={nodes.Scene068_2.geometry} material={materials.Walls_4} />
          <mesh geometry={nodes.Scene068_3.geometry} material={materials.Doors} />
          <mesh geometry={nodes.Scene068_4.geometry} material={materials.Plinth_3} />
          <mesh geometry={nodes.Scene068_5.geometry} material={materials.Roof} />
          <mesh geometry={nodes.Scene068_6.geometry} material={materials.Stairs} />
          <mesh geometry={nodes.Scene068_7.geometry} material={materials.Brick_walls_2_1} />
          <mesh geometry={nodes.Scene068_8.geometry} material={materials.Brick_walls_1} />
          <mesh geometry={nodes.Scene068_9.geometry} material={materials.Walls_1_3} />
          <mesh geometry={nodes.Scene068_10.geometry} material={materials.Windows} />
          <mesh geometry={nodes.Scene068_11.geometry} material={materials.Airing} />
          <mesh geometry={nodes.Scene068_12.geometry} material={materials.Wall_clumb} />
          <mesh geometry={nodes.Scene068_13.geometry} material={materials.Walls_3} />
          <mesh geometry={nodes.Scene068_14.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Scene068_15.geometry} material={materials.Walls_2_3} />
          <mesh geometry={nodes.Scene068_16.geometry} material={materials.Walls_3_2} />
          <mesh geometry={nodes.Scene068_17.geometry} material={materials.Walls_5} />
          <mesh geometry={nodes.Scene068_18.geometry} material={materials.Walls_1} />
          <mesh geometry={nodes.Scene068_19.geometry} material={materials.Plinth_2} />
          <mesh geometry={nodes.Scene068_20.geometry} material={materials.Brick_walls_1_1} />
        </group>
        <mesh geometry={nodes.Wall_clumb__6_.geometry} material={materials.Wall_clumb} position={[300, 300, -830]} />
      </group>
      <group position={[-31.236, -10.928, 5.103]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-382.259, 455.264, -949.329]}>
          <mesh geometry={nodes.Scene068.geometry} material={materials.Solar_panel} />
          <mesh geometry={nodes.Scene068_1.geometry} material={materials.Parts} />
          <mesh geometry={nodes.Scene068_2.geometry} material={materials.Walls_4} />
          <mesh geometry={nodes.Scene068_3.geometry} material={materials.Doors} />
          <mesh geometry={nodes.Scene068_4.geometry} material={materials.Plinth_3} />
          <mesh geometry={nodes.Scene068_5.geometry} material={materials.Roof} />
          <mesh geometry={nodes.Scene068_6.geometry} material={materials.Stairs} />
          <mesh geometry={nodes.Scene068_7.geometry} material={materials.Brick_walls_2_1} />
          <mesh geometry={nodes.Scene068_8.geometry} material={materials.Brick_walls_1} />
          <mesh geometry={nodes.Scene068_9.geometry} material={materials.Walls_1_3} />
          <mesh geometry={nodes.Scene068_10.geometry} material={materials.Windows} />
          <mesh geometry={nodes.Scene068_11.geometry} material={materials.Airing} />
          <mesh geometry={nodes.Scene068_12.geometry} material={materials.Wall_clumb} />
          <mesh geometry={nodes.Scene068_13.geometry} material={materials.Walls_3} />
          <mesh geometry={nodes.Scene068_14.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Scene068_15.geometry} material={materials.Walls_2_3} />
          <mesh geometry={nodes.Scene068_16.geometry} material={materials.Walls_3_2} />
          <mesh geometry={nodes.Scene068_17.geometry} material={materials.Walls_5} />
          <mesh geometry={nodes.Scene068_18.geometry} material={materials.Walls_1} />
          <mesh geometry={nodes.Scene068_19.geometry} material={materials.Plinth_2} />
          <mesh geometry={nodes.Scene068_20.geometry} material={materials.Brick_walls_1_1} />
        </group>
      </group>
      <group position={[-14.723, -10.928, 5.266]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Wall_clumb__4__3.geometry} material={materials.Wall_clumb} position={[0, -300, -945]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Wall_clumb__5__1.geometry} material={materials.Wall_clumb} position={[350, -300, -945]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Wall_clumb__6__1.geometry} material={materials.Wall_clumb} position={[-350, -300, -945]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Airing_1__5_.geometry} material={materials.Airing} position={[-400, -175, -1169.5]} />
        <mesh geometry={nodes.Airing_1__6_.geometry} material={materials.Airing} position={[-400, 175, -1169.5]} />
        <mesh geometry={nodes.Airing_1__7_.geometry} material={materials.Airing} position={[400, -175, -1169.5]} />
        <mesh geometry={nodes.Airing_1__8_.geometry} material={materials.Airing} position={[400, 175, -1169.5]} />
        <mesh geometry={nodes.Airing_3__3_.geometry} material={materials.Airing} position={[-250, 0, -1169.5]} />
        <mesh geometry={nodes.Airing_3__4_.geometry} material={materials.Airing} position={[250, 0, -1169.5]} />
        <mesh geometry={nodes.Airing_4__10_.geometry} material={materials.Airing} position={[-500, -125, -1169.5]} rotation={[0, 0, 1.571]} />
        <mesh geometry={nodes.Airing_4__11_.geometry} material={materials.Airing} position={[-500, 125, -1169.5]} rotation={[0, 0, 1.571]} />
        <mesh geometry={nodes.Airing_4__12_.geometry} material={materials.Airing} position={[-500, 225, -1169.5]} rotation={[0, 0, 1.571]} />
        <mesh geometry={nodes.Airing_4__13_.geometry} material={materials.Airing} position={[500, 225, -1169.5]} rotation={[0, 0, -1.571]} />
        <mesh geometry={nodes.Airing_4__14_.geometry} material={materials.Airing} position={[500, 125, -1169.5]} rotation={[0, 0, -1.571]} />
        <mesh geometry={nodes.Airing_4__15_.geometry} material={materials.Airing} position={[500, -125, -1169.5]} rotation={[0, 0, -1.571]} />
        <mesh geometry={nodes.Airing_4__16_.geometry} material={materials.Airing} position={[500, -225, -1169.5]} rotation={[0, 0, -1.571]} />
        <mesh geometry={nodes.Airing_4__9_.geometry} material={materials.Airing} position={[-500, -225, -1169.5]} rotation={[0, 0, 1.571]} />
        <mesh geometry={nodes.Building_6_Decor_1.geometry} material={materials.Walls_3} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Building_6_Decor_2.geometry} material={materials.Walls_1} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Building_6_Decor_3.geometry} material={materials.Walls_4} rotation={[-1.57, 0, 0]} />
        <mesh geometry={nodes.Building_6_Doors.geometry} material={materials.Doors} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Building_6_Plinth.geometry} material={materials.Plinth_3} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Building_6_Roof.geometry} material={materials.Roof} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Building_6_Stairs.geometry} material={materials.Stairs} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Building_6_Walls_1.geometry} material={materials.Brick_walls_2_1} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Building_6_Walls_2.geometry} material={materials.Brick_walls_1_1} rotation={[-Math.PI / 2, 0, 0]} />
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Scene078.geometry} material={materials.Walls_5} />
          <mesh geometry={nodes.Scene078_1.geometry} material={materials.Walls_6} />
          <mesh geometry={nodes.Scene078_2.geometry} material={materials.Walls_1} />
          <mesh geometry={nodes.Scene078_3.geometry} material={materials.Walls_4} />
          <mesh geometry={nodes.Scene078_4.geometry} material={materials.Doors} />
          <mesh geometry={nodes.Scene078_5.geometry} material={materials.Plinth_1} />
          <mesh geometry={nodes.Scene078_6.geometry} material={materials.Roof} />
          <mesh geometry={nodes.Scene078_7.geometry} material={materials.Stairs} />
          <mesh geometry={nodes.Scene078_8.geometry} material={materials.Walls_5_2} />
          <mesh geometry={nodes.Scene078_9.geometry} material={materials.Walls_1_2} />
          <mesh geometry={nodes.Scene078_10.geometry} material={materials.Walls_2_2} />
          <mesh geometry={nodes.Scene078_11.geometry} material={materials.Windows} />
          <mesh geometry={nodes.Scene078_12.geometry} material={materials.Airing} />
          <mesh geometry={nodes.Scene078_13.geometry} material={materials.Wall_clumb} />
          <mesh geometry={nodes.Scene078_14.geometry} material={materials.Shutters} />
        </group>
        <mesh geometry={nodes.Building_6_Walls_4.geometry} material={materials.Walls_2} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Building_6_Windows.geometry} material={materials.Windows} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Shutter_2_1__5_.geometry} material={materials.Shutters} position={[-604.5, -63, 0]} rotation={[0, 0, -1.768]} />
        <mesh geometry={nodes.Shutter_2_1__6_.geometry} material={materials.Shutters} position={[-604.5, -63, -290.4]} rotation={[0, 0, -1.768]} />
        <mesh geometry={nodes.Shutter_2_1__7_.geometry} material={materials.Shutters} position={[-604.5, -63, -579.9]} rotation={[0, 0, -1.744]} />
        <mesh geometry={nodes.Shutter_2_1__8_.geometry} material={materials.Shutters} position={[-604.5, -63, -870.4]} rotation={[0, 0, -1.955]} />
        <mesh geometry={nodes.Shutter_2_2__5_.geometry} material={materials.Shutters} position={[-604.5, 63, 0]} rotation={[0, 0, -1.496]} />
        <mesh geometry={nodes.Shutter_2_2__6_.geometry} material={materials.Shutters} position={[-604.5, 63, -290.4]} rotation={[0, 0, -1.496]} />
        <mesh geometry={nodes.Shutter_2_2__7_.geometry} material={materials.Shutters} position={[-604.5, 63, -579.9]} rotation={[0, 0, -1.352]} />
        <mesh geometry={nodes.Shutter_2_2__8_.geometry} material={materials.Shutters} position={[-604.5, 63, -870.4]} rotation={[0, 0, -1.415]} />
      </group>
      <group position={[23.351, -10.928, 6.789]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene087.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene087_1.geometry} material={materials.Walls_3} />
        <mesh geometry={nodes.Scene087_2.geometry} material={materials.Walls_4} />
        <mesh geometry={nodes.Scene087_3.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene087_4.geometry} material={materials.Plinth_2} />
        <mesh geometry={nodes.Scene087_5.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene087_6.geometry} material={materials.Walls_2_2} />
        <mesh geometry={nodes.Scene087_7.geometry} material={materials.Brick_walls_1} />
        <mesh geometry={nodes.Scene087_8.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene087_9.geometry} material={materials.Awnings_2} />
        <mesh geometry={nodes.Scene087_10.geometry} material={materials.Walls_1} />
        <mesh geometry={nodes.Scene087_11.geometry} material={materials.Airing} />
        <mesh geometry={nodes.Scene087_12.geometry} material={materials.Walls_6} />
        <mesh geometry={nodes.Scene087_13.geometry} material={materials.Awnings} />
      </group>
      <group position={[36.975, -12.746, -8.743]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene087.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene087_1.geometry} material={materials.Walls_3} />
        <mesh geometry={nodes.Scene087_2.geometry} material={materials.Walls_4} />
        <mesh geometry={nodes.Scene087_3.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene087_4.geometry} material={materials.Plinth_2} />
        <mesh geometry={nodes.Scene087_5.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene087_6.geometry} material={materials.Walls_2_2} />
        <mesh geometry={nodes.Scene087_7.geometry} material={materials.Brick_walls_1} />
        <mesh geometry={nodes.Scene087_8.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene087_9.geometry} material={materials.Awnings_2} />
        <mesh geometry={nodes.Scene087_10.geometry} material={materials.Walls_1} />
        <mesh geometry={nodes.Scene087_11.geometry} material={materials.Airing} />
        <mesh geometry={nodes.Scene087_12.geometry} material={materials.Walls_6} />
        <mesh geometry={nodes.Scene087_13.geometry} material={materials.Awnings} />
      </group>
      <group position={[-10.729, -10.928, -28.411]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Shutter_4_1__18_.geometry} material={materials.Shutters} position={[-704.4, -197, -1450]} rotation={[0, 0, -1.714]} />
        <mesh geometry={nodes.Shutter_4_2__18_.geometry} material={materials.Shutters} position={[-704.4, -102, -1450]} rotation={[0, 0, -1.386]} />
        <mesh geometry={nodes.Scene097.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene097_1.geometry} material={materials.Walls_3} />
        <mesh geometry={nodes.Scene097_2.geometry} material={materials.Walls_4} />
        <mesh geometry={nodes.Scene097_3.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene097_4.geometry} material={materials.Plinth_3} />
        <mesh geometry={nodes.Scene097_5.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene097_6.geometry} material={materials.Brick_walls_1_1} />
        <mesh geometry={nodes.Scene097_7.geometry} material={materials.Walls_2_2} />
        <mesh geometry={nodes.Scene097_8.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene097_9.geometry} material={materials.Airing} />
        <mesh geometry={nodes.Scene097_10.geometry} material={materials.Awnings_2} />
        <mesh geometry={nodes.Scene097_11.geometry} material={materials.Shutters} />
        <mesh geometry={nodes.Scene097_12.geometry} material={materials.Walls_2} />
        <mesh geometry={nodes.Scene097_13.geometry} material={materials.Walls_1} />
        <mesh geometry={nodes.Scene097_14.geometry} material={materials.Walls_6} />
        <mesh geometry={nodes.Scene097_15.geometry} material={materials.Walls_1_3} />
        <mesh geometry={nodes.Scene097_16.geometry} material={materials.Awnings} />
      </group>
      <group position={[-31.429, -10.928, -21.711]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene097.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene097_1.geometry} material={materials.Walls_3} />
        <mesh geometry={nodes.Scene097_2.geometry} material={materials.Walls_4} />
        <mesh geometry={nodes.Scene097_3.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene097_4.geometry} material={materials.Plinth_3} />
        <mesh geometry={nodes.Scene097_5.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene097_6.geometry} material={materials.Brick_walls_1_1} />
        <mesh geometry={nodes.Scene097_7.geometry} material={materials.Walls_2_2} />
        <mesh geometry={nodes.Scene097_8.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene097_9.geometry} material={materials.Airing} />
        <mesh geometry={nodes.Scene097_10.geometry} material={materials.Awnings_2} />
        <mesh geometry={nodes.Scene097_11.geometry} material={materials.Shutters} />
        <mesh geometry={nodes.Scene097_12.geometry} material={materials.Walls_2} />
        <mesh geometry={nodes.Scene097_13.geometry} material={materials.Walls_1} />
        <mesh geometry={nodes.Scene097_14.geometry} material={materials.Walls_6} />
        <mesh geometry={nodes.Scene097_15.geometry} material={materials.Walls_1_3} />
        <mesh geometry={nodes.Scene097_16.geometry} material={materials.Awnings} />
      </group>
      <group position={[8.371, -10.928, -23.211]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Awning_2__10__1.geometry} material={materials.Awnings_2} position={[300, 500, -310]} />
        <mesh geometry={nodes.Awning_2__11__1.geometry} material={materials.Awnings_2} position={[300, 500, -560]} />
        <mesh geometry={nodes.Awning_2__12__1.geometry} material={materials.Awnings_2} position={[300, 500, -810]} />
        <mesh geometry={nodes.Awning_2__13__1.geometry} material={materials.Awnings_2} position={[300, 500, -1060]} />
        <mesh geometry={nodes.Awning_2__14__1.geometry} material={materials.Awnings_2} position={[300, 500, -1310]} />
        <mesh geometry={nodes.Awning_2__15__3.geometry} material={materials.Awnings_2} position={[300, 500, -1560]} />
        <mesh geometry={nodes.Awning_2__16__3.geometry} material={materials.Awnings_2} position={[300, 500, -1810]} />
        <mesh geometry={nodes.Scene103.geometry} material={materials.Walls_4} />
        <mesh geometry={nodes.Scene103_1.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene103_2.geometry} material={materials.Plinth_3} />
        <mesh geometry={nodes.Scene103_3.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene103_4.geometry} material={materials.Walls_1} />
        <mesh geometry={nodes.Scene103_5.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene103_6.geometry} material={materials.Brick_walls_2_1} />
        <mesh geometry={nodes.Scene103_7.geometry} material={materials.Brick_walls_2} />
        <mesh geometry={nodes.Scene103_8.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene103_9.geometry} material={materials.Airing} />
        <mesh geometry={nodes.Scene103_10.geometry} material={materials.Awnings_2} />
        <mesh geometry={nodes.Scene103_11.geometry} material={materials.Walls_2_2} />
        <mesh geometry={nodes.Scene103_12.geometry} material={materials.Walls_6} />
        <mesh geometry={nodes.Scene103_13.geometry} material={materials.Brick_walls_1} />
      </group>
      <group position={[7.921, -10.928, 8.479]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene106.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene106_1.geometry} material={materials.Walls_1} />
        <mesh geometry={nodes.Scene106_2.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene106_3.geometry} material={materials.Plinth_3} />
        <mesh geometry={nodes.Scene106_4.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene106_5.geometry} material={materials.Brick_walls_2_1} />
        <mesh geometry={nodes.Scene106_6.geometry} material={materials.Brick_walls_2} />
        <mesh geometry={nodes.Scene106_7.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene106_8.geometry} material={materials.Airing} />
        <mesh geometry={nodes.Scene106_9.geometry} material={materials.Awnings_2} />
      </group>
      <group position={[-31.029, -10.928, 23.089]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene121.geometry} material={materials.Walls_5} />
        <mesh geometry={nodes.Scene121_1.geometry} material={materials.Parts} />
        <mesh geometry={nodes.Scene121_2.geometry} material={materials.Walls_3} />
        <mesh geometry={nodes.Scene121_3.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene121_4.geometry} material={materials.Plinth_1} />
        <mesh geometry={nodes.Scene121_5.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene121_6.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene121_7.geometry} material={materials.Walls_2} />
        <mesh geometry={nodes.Scene121_8.geometry} material={materials.Walls_4_2} />
        <mesh geometry={nodes.Scene121_9.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene121_10.geometry} material={materials.Airing} />
        <mesh geometry={nodes.Scene121_11.geometry} material={materials.Awnings_2} />
        <mesh geometry={nodes.Scene121_12.geometry} material={materials.Shutters} />
        <mesh geometry={nodes.Scene121_13.geometry} material={materials.Walls_4} />
        <mesh geometry={nodes.Scene121_14.geometry} material={materials.Plinth_3} />
        <mesh geometry={nodes.Scene121_15.geometry} material={materials.Walls_2_3} />
        <mesh geometry={nodes.Scene121_16.geometry} material={materials.Walls_5_2} />
      </group>
      <group position={[-11.409, -10.928, 23.439]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Scene121.geometry} material={materials.Walls_5} />
        <mesh geometry={nodes.Scene121_1.geometry} material={materials.Parts} />
        <mesh geometry={nodes.Scene121_2.geometry} material={materials.Walls_3} />
        <mesh geometry={nodes.Scene121_3.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene121_4.geometry} material={materials.Plinth_1} />
        <mesh geometry={nodes.Scene121_5.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene121_6.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene121_7.geometry} material={materials.Walls_2} />
        <mesh geometry={nodes.Scene121_8.geometry} material={materials.Walls_4_2} />
        <mesh geometry={nodes.Scene121_9.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene121_10.geometry} material={materials.Airing} />
        <mesh geometry={nodes.Scene121_11.geometry} material={materials.Awnings_2} />
        <mesh geometry={nodes.Scene121_12.geometry} material={materials.Shutters} />
        <mesh geometry={nodes.Scene121_13.geometry} material={materials.Walls_4} />
        <mesh geometry={nodes.Scene121_14.geometry} material={materials.Plinth_3} />
        <mesh geometry={nodes.Scene121_15.geometry} material={materials.Walls_2_3} />
        <mesh geometry={nodes.Scene121_16.geometry} material={materials.Walls_5_2} />
      </group>
      <group position={[12.471, -10.928, 27.289]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Wall_clumb__6__2.geometry} material={materials.Wall_clumb} position={[0, -402.002, -620.3]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Wall_clumb__7__1.geometry} material={materials.Wall_clumb} position={[0, -402.002, -911.3]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Wall_clumb__8__1.geometry} material={materials.Wall_clumb} position={[0, -402.002, -1193.3]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Airing_2__1__3.geometry} material={materials.Airing} position={[-633, -200, -1698.5]} />
        <mesh geometry={nodes.Awning_1__15_.geometry} material={materials.Awnings} position={[500, -350, -310]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Awning_1__18_.geometry} material={materials.Awnings} position={[500, -350, -600]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Awning_1__20_.geometry} material={materials.Awnings} position={[0, -400, -600]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Awning_1__21_.geometry} material={materials.Awnings} position={[500, -350, -890]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Awning_1__22_.geometry} material={materials.Awnings} position={[-500, -350, -890]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Awning_1__23_.geometry} material={materials.Awnings} position={[0, -400, -890]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Awning_1__24_.geometry} material={materials.Awnings} position={[-500, -350, -1180]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Awning_1__25_.geometry} material={materials.Awnings} position={[0, -400, -1180]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Awning_1__26_.geometry} material={materials.Awnings} position={[-500, -350, -1460]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Awning_3__12__1.geometry} material={materials.Awnings} position={[-750, -150, -1470]} rotation={[0, 0, 1.571]} scale={0.9} />
        <mesh geometry={nodes.Awning_3__15__1.geometry} material={materials.Awnings} position={[750, -150, -625]} rotation={[0, 0, -1.571]} scale={0.9} />
        <mesh geometry={nodes.Awning_3__17__1.geometry} material={materials.Awnings} position={[750, -150, -914]} rotation={[0, 0, -1.571]} scale={0.9} />
        <mesh geometry={nodes.Scene129.geometry} material={materials.Tile_1} />
        <mesh geometry={nodes.Scene129_1.geometry} material={materials.Walls_6} />
        <mesh geometry={nodes.Scene129_2.geometry} material={materials.Doors} />
        <mesh geometry={nodes.Scene129_3.geometry} material={materials.Parts} />
        <mesh geometry={nodes.Scene129_4.geometry} material={materials.Plinth_3} />
        <mesh geometry={nodes.Scene129_5.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Scene129_6.geometry} material={materials.Stairs} />
        <mesh geometry={nodes.Scene129_7.geometry} material={materials.Brick_walls_1_1} />
        <mesh geometry={nodes.Scene129_8.geometry} material={materials.Walls_6_2} />
        <mesh geometry={nodes.Scene129_9.geometry} material={materials.Walls_2_3} />
        <mesh geometry={nodes.Scene129_10.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Scene129_11.geometry} material={materials.Airing} />
        <mesh geometry={nodes.Scene129_12.geometry} material={materials.Awnings} />
        <mesh geometry={nodes.Scene129_13.geometry} material={materials.Wall_clumb} />
      </group>
      <group position={[32.771, -10.928, 25.589]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Scene078.geometry} material={materials.Walls_5} />
          <mesh geometry={nodes.Scene078_1.geometry} material={materials.Walls_6} />
          <mesh geometry={nodes.Scene078_2.geometry} material={materials.Walls_1} />
          <mesh geometry={nodes.Scene078_3.geometry} material={materials.Walls_4} />
          <mesh geometry={nodes.Scene078_4.geometry} material={materials.Doors} />
          <mesh geometry={nodes.Scene078_5.geometry} material={materials.Plinth_1} />
          <mesh geometry={nodes.Scene078_6.geometry} material={materials.Roof} />
          <mesh geometry={nodes.Scene078_7.geometry} material={materials.Stairs} />
          <mesh geometry={nodes.Scene078_8.geometry} material={materials.Walls_5_2} />
          <mesh geometry={nodes.Scene078_9.geometry} material={materials.Walls_1_2} />
          <mesh geometry={nodes.Scene078_10.geometry} material={materials.Walls_2_2} />
          <mesh geometry={nodes.Scene078_11.geometry} material={materials.Windows} />
          <mesh geometry={nodes.Scene078_12.geometry} material={materials.Airing} />
          <mesh geometry={nodes.Scene078_13.geometry} material={materials.Wall_clumb} />
          <mesh geometry={nodes.Scene078_14.geometry} material={materials.Shutters} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Buildings_mod.glb')
