/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Building_5.glb -o src/components/Building_5.jsx -r public/ -s -S -T 
Files: public/assets/models/Building_5.glb [2.14MB] > C:\Users\푸린\Desktop\activity\jungle\project0100\front\src\components\Building_5-transformed.glb [358.54KB] (83%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/../src/components/Building_5-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene018.geometry} material={materials['Walls_1.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_1.geometry} material={materials['Walls_1.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_2.geometry} material={materials['Wall_clumb.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_3.geometry} material={materials['Solar_panel.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_4.geometry} material={materials['Windows.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_5.geometry} material={materials['Walls_2_3.008']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_6.geometry} material={materials['Walls_1_3.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_7.geometry} material={materials['Brick_walls_1_1.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_8.geometry} material={materials['Stairs.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_9.geometry} material={materials['Roof.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_10.geometry} material={materials['Plinth_2.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_11.geometry} material={materials['Doors.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_12.geometry} material={materials['Walls_5.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_13.geometry} material={materials['Parts.010']} />
        <mesh castShadow receiveShadow geometry={nodes.Scene018_14.geometry} material={materials['Airing.014']} />
      </group>
    </group>
  )
}

useGLTF.preload('/../src/components/Building_5-transformed.glb')
