/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\assets\models\Cabin.glb -o src/components/Cabin.jsx -r public -s 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cabin(props) {
  const { nodes, materials } = useGLTF('/assets/models/Cabin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cabin.geometry} material={materials.lambert3SG} />
      <mesh castShadow receiveShadow geometry={nodes.Door_2.geometry} material={materials.lambert3SG} />
      <mesh castShadow receiveShadow geometry={nodes.Door_1.geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('/assets/models/Cabin.glb')
