/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/ToyCar-red.glb -o src/components/CarModel2.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/ToyCar-red.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Formula.geometry} material={materials.toy_Cars_color_01} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.FL_wheel.geometry} material={materials.toy_Cars_color_01} position={[77.042, 110.73, -33.979]} />
        <mesh geometry={nodes.FR_wheel.geometry} material={materials.toy_Cars_color_01} position={[-77.042, 110.73, -33.979]} />
        <mesh geometry={nodes.RL_wheel.geometry} material={materials.toy_Cars_color_01} position={[79.9, -121.805, -38.147]} />
        <mesh geometry={nodes.RR_wheel.geometry} material={materials.toy_Cars_color_01} position={[-79.9, -121.805, -38.147]} />
      </mesh>
      <mesh geometry={nodes.BreakLight_L.geometry} material={materials['red-l']} position={[0.457, 0.685, -1.808]} />
      <mesh geometry={nodes.BreakLight_R.geometry} material={materials['red-r']} position={[-0.443, 0.703, -1.808]} />
    </group>
  )
}

useGLTF.preload('/assets/models/ToyCar-red.glb')
