/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/bluecar.glb -o src/components/CarModel.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CarModel() {
  const { nodes, materials } = useGLTF('/assets/models/bluecar.glb')
  return (
    <group group scale={[0.34,0.32,0.46]} position={[0, 0, 0 ]} rotation-y={Math.PI}>
        <group position={[0, -0.25, 0]} rotation={[0, 0, 0]} scale={0.13}>
            <mesh geometry={nodes.Cube006_Cube001.geometry} material={materials.Ban} position={[0, -0.7, 0]} scale={[1.2, 1, 1.5]} />

            <mesh geometry={nodes.Circle003.geometry} material={materials.besi} position={[-2.701, 1.144, 2.949]} />
            <mesh geometry={nodes.Circle002.geometry} material={materials.besi} position={[-2.701, 1.144, -3.085]} />

            <mesh geometry={nodes.Circle001.geometry} material={materials.besi} position={[2.701, 1.144, -3.085]} />
            <group position={[0, -0.5, 0]} scale={[1.2, 1, 1.5]}>
                <mesh geometry={nodes['Cube_Cube002-Mesh'].geometry} material={materials.Ban} />
                <mesh geometry={nodes['Cube_Cube002-Mesh_1'].geometry} material={materials.Body} />
                <mesh geometry={nodes['Cube_Cube002-Mesh_2'].geometry} material={materials.Yellow} />
                <mesh geometry={nodes['Cube_Cube002-Mesh_3'].geometry} material={materials.Putih} />
            </group>
            <mesh geometry={nodes.Circle.geometry} material={materials.besi} position={[2.701, 1.144, 2.949]} />

        </group>
    </group>
  )
}

useGLTF.preload('/assets/models/bluecar.glb')
