/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/porchelow.glb -o src/components/CarModel.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CarModel(props) {
  const { nodes, materials } = useGLTF('/assets/models/porchelow.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.1, 0.035]} rotation={[Math.PI/2, 0, Math.PI]} scale={0.002}>
        <mesh geometry={nodes.CARRERA_LOW.geometry} material={materials.CARRERA_4096}>
          <mesh geometry={nodes.front_lamps_1.geometry} material={materials.CARRERA_4096} />
          <mesh geometry={nodes.rear_lamps_1.geometry} material={materials.CARRERA_4096} />
          <mesh geometry={nodes.spoiler1_1.geometry} material={materials.CARRERA_4096}>
          <mesh geometry={nodes.spoiler2_1.geometry} material={materials.CARRERA_4096} />
         </mesh>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/porchelow.glb')
