/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Chair2.glb -o src/components/Chair2.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair2(props) {
  const { nodes, materials } = useGLTF('/assets/models/Chair2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh294144946.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh294144946_1.geometry} material={materials.mat22} />
    </group>
  )
}

useGLTF.preload('/assets/models/Chair2.glb')
