/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Cliff.glb -o src/components/Cliff.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cliff(props) {
  const { nodes, materials } = useGLTF('/assets/models/Cliff.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.Cube} />
    </group>
  )
}

useGLTF.preload('/assets/models/Cliff.glb')
