/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Crab2.glb -o src/components/Crab2.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Crab2(props) {
  const { nodes, materials } = useGLTF('/assets/models/Crab2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Crab1-Mesh'].geometry} material={materials.Black} />
      <mesh geometry={nodes['Crab1-Mesh_1'].geometry} material={materials.Red} />
      <mesh geometry={nodes['Crab1-Mesh_2'].geometry} material={materials.Dark_Red} />
      <mesh geometry={nodes['Crab1-Mesh_3'].geometry} material={materials.White} />
    </group>
  )
}

useGLTF.preload('/assets/models/Crab2.glb')
