/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Cursor.glb -o src/components/Cursor.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { LayerMaterial, Depth, Fresnel } from 'lamina'

export function Cursor(props) {
  const { nodes, materials } = useGLTF('/assets/models/Cursor.glb')
  const ref = useRef()
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material}>
        <LayerMaterial ref={ref} toneMapped={false} color="red">
          <Fresnel mode="add" color="white" intensity={0.5} power={1.5} bias={0.05} />
        </LayerMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/assets/models/Cursor.glb')
