/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/DarkUmbrella.glb -o src/components/DarkUmbrella.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DarkUmbrella(props) {
  const { nodes, materials } = useGLTF('/assets/models/DarkUmbrella.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1776344293.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh822346014.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh822346014_1.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh822346014_2.geometry} material={materials.mat22} />
    </group>
  )
}

useGLTF.preload('/assets/models/DarkUmbrella.glb')
