/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\assets\models\Hut.glb -o src/components/Hut.jsx -r public -s 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hut(props) {
  const { nodes, materials } = useGLTF('/assets/models/Hut.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.SM_HutSM_Hut_1.geometry} material={materials.lambert2SG} />
      <mesh castShadow receiveShadow geometry={nodes.SM_HutSM_Hut_1_1.geometry} material={materials.lambert4SG} />
      <mesh castShadow receiveShadow geometry={nodes.SM_HutSM_Hut_1_2.geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('/assets/models/Hut.glb')
