/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\assets\models\Bamboo.glb -o src/components/Plants.jsx -r public -s 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bamboo(props) {
  const { nodes, materials } = useGLTF('/assets/models/Bamboo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.bamboo.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('/assets/models/Bamboo.glb')

export function FlowerBush(props) {
  const { nodes, materials } = useGLTF('/assets/models/FlowerBushes.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Petals_1.geometry} material={materials.Flowers} position={[150.856, 0, 0]} rotation={[1.514, -0.461, -0.465]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Plant_2.geometry} material={materials.Flowers} position={[152.739, 0, 0]} rotation={[-1.447, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Plant_Flowers.geometry} material={materials.Flowers} position={[154.809, 0, 0]} rotation={[-1.362, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/assets/models/FlowerBushes.glb')

