/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/PoliceCar.glb -o src/components/PoliceCar.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PoliceCar(props) {
  const { nodes, materials } = useGLTF('/assets/models/PoliceCar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Police_Car_Cube025_1.geometry} material={materials.FFFFFF} />
      <mesh geometry={nodes.Police_Car_Cube025_1_1.geometry} material={materials['80DEEA']} />
      <mesh geometry={nodes.Police_Car_Cube025_1_2.geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes.Police_Car_Cube025_1_3.geometry} material={materials['455A64']} />
      <mesh geometry={nodes.Police_Car_Cube025_1_4.geometry} material={materials['039BE5']} />
      <mesh geometry={nodes.Police_Car_Cube025_1_5.geometry} material={materials.F44336} />
    </group>
  )
}

useGLTF.preload('/assets/models/PoliceCar.glb')
