/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/resort-ocean_small.glb -o src/components/resort-ocean_small.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ResortOceanSmall(props) {
  const { nodes, materials } = useGLTF('/assets/models/resort-ocean_small.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ocean.geometry} material={materials.LowPolyWaterMaterial} rotation={[Math.PI / 2, 0, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('/assets/models/resort-ocean_small.glb')
