/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Seagull2.glb -o src/components/Seagull2.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import ColliderBox from '../ColliderBox'
export function Seagull2(props) {
  const { nodes, materials } = useGLTF('/assets/models/Seagull2.glb')
  const position=props.position
  const rotation= props.rotation
  return (
    <group {...props} dispose={null}>
      <ColliderBox scale={[1.7, 5, 1]} position={[position[0]-0.5, position[1]-1, position[2]+0.5]} rotation={rotation}/>
      <mesh castShadow geometry={nodes.Geo_Seagull.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/assets/models/Seagull2.glb')
