/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Seagull2.glb -o src/components/Seagull2.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Seagull2(props) {
  const { nodes, materials } = useGLTF('/assets/models/Seagull2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Geo_Seagull.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/assets/models/Seagull2.glb')
