/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\assets\models\skyBox.glb -o src/components/SkyCube.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SkyCube(props) {
  const { nodes, materials } = useGLTF('/assets/models/skyBox.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.큐브.geometry} material={materials['매테리얼.005']} />
    </group>
  )
}

useGLTF.preload('/assets/models/skyBox.glb')
