/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\assets\models\startline.glb -o src/components/startline.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Startline(props) {
  const { nodes, materials } = useGLTF('/assets/models/startline.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={[4, 1, 4]}>
        <mesh geometry={nodes.mesh7783894.geometry} material={materials.mat21} />
        <mesh geometry={nodes.mesh7783894_1.geometry} material={materials.mat23} />
        <mesh geometry={nodes.mesh7783894_2.geometry} material={materials['mat21.001']} />
        <mesh geometry={nodes.mesh7783894_3.geometry} material={materials['mat23.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/startline.glb')
