/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Stone Wall.glb -o src/Map2/StoneWall.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StoneWall(props) {
  const { nodes, materials } = useGLTF('/assets/models/Stone Wall.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[6000, 5000, 5000]}>
        <mesh geometry={nodes.Wall_SecondAge_1.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Wall_SecondAge_2.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Wall_SecondAge_3.geometry} material={materials.Wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Stone Wall.glb')
