/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/StreetVendorCart.glb -o src/components/StreetVendorCart.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StreetVendorCart(props) {
  const { nodes, materials } = useGLTF('/assets/models/StreetVendorCart.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group2137811205.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group836827319.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group2129825026.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group848789661.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1114076226.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group2047872067.geometry} material={materials.mat24} />
      <mesh geometry={nodes.group1807915310.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1268663749.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1802341655.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group600178558.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group788047614.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group174170572.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1680523390.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1635635275.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1467488461.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1130873769.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group2104123109.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1167464278.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group166399929.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1619515531.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group938209853.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group506402616.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group876795995.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group328140900.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group45740939.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group132533053.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1287363148.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group636553527.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group496196789.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group112617297.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1828721487.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group570559936.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group257275669.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group211861406.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1521577097.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group76525473.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1633208947.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group490608219.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1986277788.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1568070331.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group565023227.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1532671458.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1445051624.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1599581727.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1052900010.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group2118986946.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1823860208.geometry} material={materials.mat24} />
      <mesh geometry={nodes.group138830770.geometry} material={materials.mat24} />
      <mesh geometry={nodes.group728447653.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group170467204.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1260492988.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group604987152.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group113263190.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group652222982.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1653700673.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group164225269.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1687385456.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group50178752.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1594283966.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1626333558.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group758814236.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group435715700.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1734167987.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group498359861.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1742358140.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1576294771.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group325230731.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1734565655.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group289408600.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1893631097.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group276127160.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1681273695.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group338717678.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1602146334.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1674686895.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1206797869.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group617186935.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1943061558.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1898051402.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group2026830817.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group756296148.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1218920521.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group525132657.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1025956456.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh784883372.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh784883372_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1038552300.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1038552300_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh620847934.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh620847934_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh722820718.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh722820718_1.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh156199534.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh156199534_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1280774605.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1280774605_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1824758900.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1824758900_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1824758900_2.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh741611477.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh741611477_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh741611477_2.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh2048164464.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh2048164464_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh2048164464_2.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh172438420.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh172438420_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh57093529.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh57093529_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh468951739.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh468951739_1.geometry} material={materials.mat16} />
    </group>
  )
}

useGLTF.preload('/assets/models/StreetVendorCart.glb')
