/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\assets\models\Surfboard.glb -o src/components/Surfboard.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Surfboard(props) {
  const { nodes, materials } = useGLTF('/assets/models/Surfboard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Surfboard_Cube027_1.geometry} material={materials.FFFFFF} />
      <mesh castShadow receiveShadow geometry={nodes.Surfboard_Cube027_1_1.geometry} material={materials.F44336} />
    </group>
  )
}

useGLTF.preload('/assets/models/Surfboard.glb')
