/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Surfboard2.glb -o src/components/Surfboard2.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Surfboard2(props) {
  const { nodes, materials } = useGLTF('/assets/models/Surfboard2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Mat.1']} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/assets/models/Surfboard2.glb')
