/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/bushs.glb -o src/components/Trees.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Palm_1(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh castShadow geometry={nodes.Palm_1.geometry} material={materials.Palms} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function Palm_2(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh castShadow geometry={nodes.Palm_2.geometry} material={materials.Palms} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function Palm_3(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh castShadow geometry={nodes.Palm_3.geometry} material={materials.Palms} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function Palm_4(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh castShadow geometry={nodes.Palm_4.geometry} material={materials.Palms} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function Palm_5(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh castShadow geometry={nodes.Palm_5.geometry} material={materials.Palms} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function Clumb_1(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh geometry={nodes.Clumb_1.geometry} material={materials.Clumbs} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Palm_1_1.geometry} material={materials.Palms} />
      </mesh>
    </group>
  )
}

export function Clumb_2(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh geometry={nodes.Clumb_2.geometry} material={materials.Clumbs}rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Palm_2_1.geometry} material={materials.Palms}/>
      </mesh>
    </group>
  )
}

export function Clumb_3(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh geometry={nodes.Clumb_3.geometry} material={materials.Clumbs} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Palm_3_1.geometry} material={materials.Palms} />
      </mesh>
    </group>
  )
}

export function Clumb_4(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh geometry={nodes.Clumb_4.geometry} material={materials.Clumbs} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Palm_4_1.geometry} material={materials.Palms}/>
      </mesh>
    </group>
  )
}

export function Clumb_5(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh geometry={nodes.Clumb_5.geometry} material={materials.Clumbs}rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Palm_5_1.geometry} material={materials.Palms} />
      </mesh>
    </group>
  )
}

export function Clumb_6(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh geometry={nodes.Clumb_6.geometry} material={materials.Clumbs}rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Bush_3.geometry} material={materials.Plants} />
      </mesh>
    </group>
  )
}

export function Clumb_7(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh geometry={nodes.Clumb_7.geometry} material={materials.Clumbs} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Bush_2.geometry} material={materials.Plants} scale={1.3} />
      </mesh>
    </group>
  )
}

export function Clumb_8(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>   
      <mesh geometry={nodes.Clumb_8.geometry} material={materials.Clumbs} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Bush_1.geometry} material={materials.Plants} scale={[1.335, 1.35, 1.35]} />
      </mesh>
    </group>
  )
}

export function Bush_1(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Bush_1_1.geometry} material={materials.Plants}rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function Bush_2(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Bush_2_1.geometry} material={materials.Plants} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

export function Bush_3(props) {
  const { nodes, materials } = useGLTF('/assets/models/bushs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Bush_3_1.geometry} material={materials.Plants} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/assets/models/bushs.glb')

