/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/WallWindow.glb -o src/components/WallWindow.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WallWindow(props) {
  const { nodes, materials } = useGLTF('/assets/models/WallWindow.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, 0]} scale={[100, 100, 5.973]}>
        <mesh geometry={nodes.Window_Bars_1.geometry} material={materials.Highlights} />
        <mesh geometry={nodes.Window_Bars_2.geometry} material={materials.Main} />
        <mesh geometry={nodes.Window_Bars_3.geometry} material={materials.Metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/WallWindow.glb')
