/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Royalboard.glb -o src/components/Ruins/Tiles.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/Royalboard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cuttingBoard_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.cuttingBoard_1_1.geometry} material={materials.brown} />
    </group>
  )
}

useGLTF.preload('/assets/models/Royalboard.glb')
