/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/WhiteWall.glb -o src/Castle/Object/WhiteWall.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WhiteWall(props) {
  const { nodes, materials } = useGLTF('/assets/models/WhiteWall.glb')
  return (
    <group {...props} dispose={null}>
        <group rotation={[Math.PI/2 , Math.PI/2 , 0]} scale={[30, 0.01, 10]}>
            <mesh geometry={nodes.p000086735.geometry} material={materials['0.BaseMaterial']} />
        </group>
    </group>
  )
}

export function WhiteWall1(props) {
    const { nodes, materials } = useGLTF('/assets/models/WhiteWall.glb')
    return (
      <group {...props} dispose={null}>
          <group rotation={[Math.PI/2 , Math.PI/2 , 0]} scale={[30, 0.01, 12.5]}>
              <mesh geometry={nodes.p000086735.geometry} material={materials['0.BaseMaterial']} />
          </group>
      </group>
    )
  }

export function WhiteWall2(props) {
    const { nodes, materials } = useGLTF('/assets/models/WhiteWall.glb')
    return (
      <group {...props} dispose={null}>
          <group rotation={[0 , 0 , Math.PI/2]} scale={[30, 0.01, 6.5]}>
              <mesh geometry={nodes.p000086735.geometry} material={materials['0.BaseMaterial']} />
          </group>
      </group>
    )
  }

useGLTF.preload('/assets/models/WhiteWall.glb')