/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/YellowWall.glb -o src/components/Map/YellowWall.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function YellowWall(props) {
  const { nodes, materials } = useGLTF('/assets/models/YellowWall.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Wall_Modular_1.geometry} material={materials.Wall_Dark} />
        <mesh geometry={nodes.Wall_Modular_2.geometry} material={materials.Wall_Medium} />
        <mesh geometry={nodes.Wall_Modular_3.geometry} material={materials.Wall_Highlights} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/YellowWall.glb')
